// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfacrwnnvwhllxjcjkdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmYWNyd25udndobGx4amNqa2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NzgzODYsImV4cCI6MjA1NDI1NDM4Nn0.TVlVq-khAAUSS-_lNE3TJi0Yc16-gzQ-2e8q9y0fkkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);